---
title: "Research"
subtitle: "Exploration through research & analysis"
---

## Research Interests

- How research and data analysis can help us better understand people, communities, and consumer behavior
- Combining quantitative and qualitative research methods to identify patterns, examine social trends, and translate findings into meaningful insights
- Topics spanning demographics, immigration, and audience insights

## Projects

### 1) Lionsgate: Understanding Audiences Through Market & Cultural Insights

[MIXED-METHODS / LIONSGATE INTERNSHIP / 2026]{.project-label}

**Research Question:** How is audience segmentation decided, and where are there opportunities to strengthen this process through marketing strategy?

**Approach:** Interviewed 7 key stakeholders from departments across the Motion Picture Group and analyze working 3 film marketing campaigns.

**Results:** Presented key findings based off of established objectives to executives. Identified 4 data-driven actionable recommendations to enhance marketing strategy.
<section id="Deliverable">
    <h2>Deliverable</h2>

    </p>

    <iframe
        src="assets/Stephanie_Pacheco_Intern_Final_Project.pdf"
        width="100%"
        height="600px"
        style="border: none;">
    </iframe>

    <p>
        <a href="assets/Stephanie_Pacheco_Intern_Final_Project.pdf" download>
            Download My Project (PDF)
        </a>
    </p>
</section>
*Removed selected slides with sensitive and proprietary information*

### 2) IIMMLA Analysis: Exploring Latino Identity Through Language, Education, & Income

[ QUANTITATIVE / SOCIOLOGICAL RESEARCH / 2026]{.project-label}

**Research Question:** When Hispanic/Latino is not offered as a racial identification category, how are measures of assimilation into U.S. society indicative of how 1.5-, second-, and third-generation Latino immigrants identify themselves?

**Approach:** Analyzed the Immigration and Intergenerational Mobility in Metropolitan Los Angeles (IIMMLA) Dataset to examine relationships between Latino identification and selected variables, including home language, education, income, age, and gender. Ran logistic regressions in R and produced Odds Ratios in 4 Models to deliver findings.

**Results:** Findings revealed support for Segmented Assimilation Theory, suggesting diverse outcomes in identity formation.
<section id="Analysis Results">
    <h2>Analysis Results</h2>

    </p>

    <iframe
        src="assets/Stephanie_Pacheco_IIMMLA_Analysis_Tables.pdf"
        width="100%"
        height="700px"
        style="border: none;">
    </iframe>

    <p>
        <a href="assets/Stephanie_Pacheco_IIMMLA_Analysis_Tables.pdf" download>
            Download My Results (PDF)
        </a>
    </p>
</section>

### 3) ACS Analysis: Limited English Proficiency & State Median Household Income

[QUANTITATIVE / DEMOGRAPHIC RESEARCH / 2026]{.project-label}

**Research Question:** How does limited English proficiency influence household income among immigrants in the United States?

**Approach:** Analyzed the American Community Survey (ACS) to examine the correlation between research variables. Conducted linear regressions and produced data visualizations in R to deliver findings.

**Results:** Statistically significant findings revealed a negative correlation, suggesting that limited English proficiency reduces access to opportunities for upward mobility and limits the ability to effectively navigate labor markets.
<section id="Deck">
    <h2>Deck</h2>

    </p>

    <iframe
        src="assets/Stephanie_Pacheco_POLS_4100_Research_Project.pdf"
        width="100%"
        height="700px"
        style="border: none;">
    </iframe>

    <p>
        <a href="assets/Stephanie_Pacheco_POLS_4100_Research_Project.pdf" download>
            Download My Deck (PDF)
        </a>
    </p>
</section>

[Questions? Let's chat!](mailto:spachec7@lion.lmu.edu){.primary-link}
